import { LegalLayout, type LegalSection } from "@/components/layout/legal-layout";
import { buildMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/site";

export const metadata = buildMetadata({
  title: "Privacy Policy",
  description: `How ${siteConfig.name} collects, uses, stores and protects personal information submitted through this website and through our software products.`,
  path: "/privacy-policy",
});

/**
 * Template privacy policy.
 *
 * Written to be accurate for this site as built (a contact form and a
 * newsletter field, no analytics, no third-party trackers). It is a starting
 * point and not legal advice — have counsel review it before launch, and update
 * it the moment analytics or a CRM is added.
 */
const SECTIONS: LegalSection[] = [
  {
    heading: "Who we are",
    paragraphs: [
      `${siteConfig.legalName} ("Plutox Tech", "we", "us") is a software development company registered in ${siteConfig.contact.address.country}, with its principal office at ${siteConfig.contact.address.street}, ${siteConfig.contact.address.city}, ${siteConfig.contact.address.region} ${siteConfig.contact.address.postalCode}.`,
      `We are the data controller for personal information collected through this website. For any question about this policy or to exercise your rights, contact us at ${siteConfig.contact.email}.`,
    ],
  },
  {
    heading: "Information we collect",
    paragraphs: [
      "We collect only what you deliberately give us. This website sets no advertising cookies, runs no third-party analytics or tracking scripts, and does not build behavioural profiles of visitors.",
      "When you submit the enquiry form or subscribe to the newsletter, we receive:",
    ],
    bullets: [
      "Contact details you enter — name, company, email address and phone number.",
      "Project context you choose to share — the service you are interested in, an approximate budget band, and your message.",
      "Standard server log data generated by any web request, including IP address, user agent and timestamp, retained briefly for security and abuse prevention.",
    ],
  },
  {
    heading: "How we use it",
    paragraphs: [
      "We use your information for a small, specific set of purposes:",
    ],
    bullets: [
      "To reply to your enquiry and, if you proceed, to scope and deliver the work.",
      "To send the newsletter, where you have explicitly subscribed. Every edition includes a one-click unsubscribe link.",
      "To keep the site secure — rate limiting, spam filtering and abuse investigation.",
      "To meet legal, tax and accounting obligations where a contract is formed.",
    ],
  },
  {
    heading: "Legal basis for processing",
    paragraphs: [
      "Where the GDPR or an equivalent regime applies, we rely on: your consent for newsletter subscriptions; the performance of a contract, or steps preparatory to one, for enquiry handling and project delivery; our legitimate interests for site security and fraud prevention; and legal obligation for statutory record keeping.",
      "You may withdraw consent for marketing at any time without affecting any processing carried out before withdrawal.",
    ],
  },
  {
    heading: "What we never do",
    paragraphs: [
      "We want to be unambiguous about this, because plenty of policies are not:",
    ],
    bullets: [
      "We do not sell, rent or trade your personal information to anyone, under any circumstances.",
      "We do not add enquiry contacts to marketing lists. Subscribing is a separate, deliberate action.",
      "We do not use your data to train machine-learning models.",
      "We do not share client project data between clients, ever.",
    ],
  },
  {
    heading: "Service providers",
    paragraphs: [
      "We use a small number of processors to operate the business — cloud hosting, transactional email delivery and accounting software. Each is bound by a data processing agreement, may only act on our instructions, and may not use your data for its own purposes.",
      "Where a processor is located outside your jurisdiction, transfers are covered by Standard Contractual Clauses or an equivalent adequacy mechanism. We can name the current processors on request.",
    ],
  },
  {
    heading: "Data security",
    paragraphs: [
      "Data is encrypted in transit using TLS and at rest by the underlying storage platform. Access follows the principle of least privilege, is limited to personnel who need it to do their job, and is logged.",
      "Our dependencies are scanned continuously in CI, backups are tested with point-in-time restore, and we run periodic penetration tests. No system is perfectly secure, but we will notify you and the relevant supervisory authority without undue delay if a breach affects your personal data.",
    ],
  },
  {
    heading: "How long we keep it",
    paragraphs: [
      "Enquiries that do not lead to an engagement are deleted within 24 months. Records relating to a signed contract are retained for the period required by tax and company law in the relevant jurisdiction, typically seven years. Newsletter subscriptions are kept until you unsubscribe. Server logs are rotated within 30 days.",
    ],
  },
  {
    heading: "Your rights",
    paragraphs: [
      "Subject to the law that applies to you, you have the right to:",
    ],
    bullets: [
      "Access the personal information we hold about you, and receive a copy of it.",
      "Correct information that is inaccurate or incomplete.",
      "Request erasure where we no longer have a lawful basis to keep it.",
      "Restrict or object to processing based on our legitimate interests.",
      "Receive your data in a portable, machine-readable format.",
      "Withdraw consent to marketing at any time.",
      "Lodge a complaint with your local data protection authority.",
    ],
  },
  {
    heading: "Cookies",
    paragraphs: [
      "This website uses a single first-party item of local storage to remember your light or dark theme preference. It is strictly functional, contains no identifier, and is not used for tracking — which is why you are not being shown a consent banner.",
      "If we ever introduce analytics or marketing cookies, we will ask for your consent before setting them and update this policy first.",
    ],
  },
  {
    heading: "Children",
    paragraphs: [
      "Our services are sold business-to-business and are not directed at children. We do not knowingly collect personal information from anyone under 16. If you believe a child has provided us with data, contact us and we will delete it.",
    ],
  },
  {
    heading: "Changes and contact",
    paragraphs: [
      "We may update this policy to reflect changes in our practices or the law. Material changes will be announced on this page with a revised date, and where required we will notify you directly.",
      `Questions, requests or complaints: ${siteConfig.contact.email}, or write to us at ${siteConfig.contact.address.street}, ${siteConfig.contact.address.city}, ${siteConfig.contact.address.country}.`,
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      description="What we collect, why we collect it, how long we keep it, and the things we will never do with it."
      lastUpdated="6 August 2026"
      sections={SECTIONS}
    />
  );
}
