/**
 * Convert the served raster images to WebP.
 *
 * Artwork is converted **losslessly**, deliberately. The brand files are the
 * supplied artwork and the standing instruction is to use them unmodified —
 * re-encoding losslessly changes the container, not a single pixel, which lossy
 * WebP could not promise. Product wordmarks are flat colour on transparency,
 * where lossless usually beats lossy anyway, so there is nothing to trade.
 *
 * Photographs are the exception and are encoded lossy at q82. Lossless WebP on a
 * continuous-tone photo lands *larger* than the JPEG it replaced, so applying the
 * artwork rule there would make the page heavier, not lighter.
 *
 * Some PNGs stay: `plutox-mark.png` feeds `generate-icons.mjs`, and the logo
 * sources now live outside `public/` in `assets/product-logos`, which feed
 * `generate-product-logos.mjs`, and `src/app/icon.png` / `apple-icon.png` are
 * Next's file-based icons, which want PNG.
 *
 * Run with:  npm run brand-webp
 */
import { readdir, rm, stat } from "node:fs/promises";
import { join } from "node:path";

import sharp from "sharp";

const ROOT = process.cwd();
const DIRS = [
  { path: join(ROOT, "public", "images", "brand"), photo: false },
  { path: join(ROOT, "public", "images", "products"), photo: false },
  { path: join(ROOT, "public", "images", "team"), photo: true },
];

const SOURCE = /\.(png|jpe?g)$/i;

/** PNGs a script or the framework still needs in that format. */
const KEEP_AS_PNG = new Set([
  "plutox-mark.png", // source for generate-icons.mjs; a .webp copy is what pages render
  "plutox-mark-rounded.png", // generated by it
]);

let before = 0;
let after = 0;
const converted = [];

for (const { path: dir, photo } of DIRS) {
  for (const file of await readdir(dir)) {
    if (!SOURCE.test(file) || KEEP_AS_PNG.has(file)) continue;

    const from = join(dir, file);
    const to = from.replace(SOURCE, ".webp");

    await sharp(from)
      .webp(photo ? { quality: 82, effort: 6 } : { lossless: true, effort: 6 })
      .toFile(to);

    const [a, b] = await Promise.all([stat(from), stat(to)]);
    before += a.size;
    after += b.size;
    converted.push(`${file} ${(a.size / 1024) | 0}KB → ${(b.size / 1024) | 0}KB`);

    await rm(from);
  }
}

for (const line of converted) console.log(`✓ ${line}`);
console.log(
  `\n${(before / 1024) | 0}KB → ${(after / 1024) | 0}KB  (${Math.round((1 - after / before) * 100)}% smaller)`,
);
